---
- name: Check nginx service status
  command: systemctl is-active nginx
  register: nginx_status
  changed_when: false

- name: Show nginx status
  debug:
    var: nginx_status.stdout

- name: Check HTTPS endpoint
  uri:
    url: https://api.psharipov.de/actuator/health
    return_content: true
  register: api_health

- name: Show API health status
  debug:
    var: api_health.status

- name: Backup nginx config
  copy:
    src: /etc/nginx/sites-available/api.psharipov.de
    dest: /etc/nginx/sites-available/api.psharipov.de.bak
    remote_src: true

- name: Validate nginx config
  command: nginx -t
  changed_when: false
